[rospy.client][INFO] 2022-02-23 12:22:13,442: init_node, name[/gripper_action_server], pid[512]
[xmlrpc][INFO] 2022-02-23 12:22:13,443: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-02-23 12:22:13,443: Started XML-RPC server [http://FM00351-u:42839/]
[rospy.init][INFO] 2022-02-23 12:22:13,443: ROS Slave URI: [http://FM00351-u:42839/]
[rospy.impl.masterslave][INFO] 2022-02-23 12:22:13,443: _ready: http://FM00351-u:42839/
[rospy.registration][INFO] 2022-02-23 12:22:13,444: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-02-23 12:22:13,444: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-02-23 12:22:13,544: registered with master
[rospy.rosout][INFO] 2022-02-23 12:22:13,544: initializing /rosout core topic
[rospy.rosout][INFO] 2022-02-23 12:22:13,548: connected to core topic /rosout
[rospy.simtime][INFO] 2022-02-23 12:22:13,550: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-02-23 12:22:13,803: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-02-23 12:22:34,982: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:22:34,982: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:22:34,982: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:22:34,988: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:42165/], count 0
[rospy.internal][INFO] 2022-02-23 12:22:34,988: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:42165/], count 0
[rosout][INFO] 2022-02-23 12:22:35,009: state: initializing
[rosout][INFO] 2022-02-23 12:22:35,010: controller is started now
[rospy.internal][INFO] 2022-02-23 12:22:35,060: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][INFO] 2022-02-23 12:22:46,797: topic[/rosout] adding connection to [/rostopic_1337_1645618966559], count 1
[rospy.internal][ERROR] 2022-02-23 12:22:59,476: Unable to initiate TCP/IP socket to FM00351-u:44697 (http://FM00351-u:42165/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-02-23 12:22:59,476: Unable to initiate TCP/IP socket to FM00351-u:44697 (http://FM00351-u:42165/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-02-23 12:22:59,501: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-02-23 12:22:59,501: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-02-23 12:22:59,502: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-02-23 12:23:00,478: Unknown error initiating TCP/IP socket to FM00351-u:44697 (http://FM00351-u:42165/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-02-23 12:23:00,479: Unknown error initiating TCP/IP socket to FM00351-u:44697 (http://FM00351-u:42165/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-02-23 12:23:00,479: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:42165/
[rospy.internal][INFO] 2022-02-23 12:23:00,480: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:42165/
[rospy.internal][INFO] 2022-02-23 12:23:01,747: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:23:01,747: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:23:01,747: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:23:01,820: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35073/], count 0
[rospy.internal][INFO] 2022-02-23 12:23:01,821: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35073/], count 0
[rospy.internal][ERROR] 2022-02-23 12:23:15,521: Unable to initiate TCP/IP socket to FM00351-u:36611 (http://FM00351-u:35073/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-02-23 12:23:15,522: Unable to initiate TCP/IP socket to FM00351-u:36611 (http://FM00351-u:35073/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-02-23 12:23:15,771: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-02-23 12:23:15,827: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-02-23 12:23:15,827: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-02-23 12:23:16,523: Unknown error initiating TCP/IP socket to FM00351-u:36611 (http://FM00351-u:35073/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-02-23 12:23:16,524: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35073/
[rospy.internal][WARNING] 2022-02-23 12:23:16,524: Unknown error initiating TCP/IP socket to FM00351-u:36611 (http://FM00351-u:35073/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-02-23 12:23:16,525: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35073/
[rospy.internal][INFO] 2022-02-23 12:23:19,830: topic[/rosout] removing connection to /rostopic_1337_1645618966559
[rospy.internal][INFO] 2022-02-23 12:23:23,543: topic[/rosout] adding connection to [/rostopic_1436_1645619003303], count 1
[rospy.internal][INFO] 2022-02-23 12:23:31,925: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:23:31,925: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:23:31,926: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-02-23 12:23:32,005: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:39931/], count 0
[rospy.internal][INFO] 2022-02-23 12:23:32,007: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:39931/], count 0
[rospy.internal][ERROR] 2022-02-23 12:23:39,637: Unable to initiate TCP/IP socket to FM00351-u:45975 (http://FM00351-u:39931/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-02-23 12:23:39,638: Unable to initiate TCP/IP socket to FM00351-u:45975 (http://FM00351-u:39931/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-02-23 12:23:39,970: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-02-23 12:23:40,008: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-02-23 12:23:40,008: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-02-23 12:23:40,639: Unknown error initiating TCP/IP socket to FM00351-u:45975 (http://FM00351-u:39931/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-02-23 12:23:40,639: Unknown error initiating TCP/IP socket to FM00351-u:45975 (http://FM00351-u:39931/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-02-23 12:23:40,640: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:39931/
[rospy.internal][INFO] 2022-02-23 12:23:40,640: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:39931/
[rospy.core][INFO] 2022-02-23 12:23:42,971: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-02-23 12:23:42,975: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-02-23 12:23:42,975: topic[/rosout] removing connection to /rostopic_1436_1645619003303
[rospy.internal][INFO] 2022-02-23 12:23:42,975: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.impl.masterslave][INFO] 2022-02-23 12:23:42,975: signal-2
[rosout][ERROR] 2022-02-23 12:23:57,818: Exception in your execute callback: unexpected EOF while parsing (<string>, line 0)
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 38, in execute
    Robotiq2FGripperSlipController().controller()
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 800, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 773, in askForInput
    return input(strAskForCommand)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

[rospy.core][INFO] 2022-02-23 12:23:57,921: signal_shutdown [atexit]
