[rospy.client][INFO] 2022-02-14 15:38:31,994: init_node, name[/fm_gripper_action_server], pid[3222]
[xmlrpc][INFO] 2022-02-14 15:38:31,995: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-02-14 15:38:31,995: Started XML-RPC server [http://FM00351-u:40347/]
[rospy.init][INFO] 2022-02-14 15:38:31,995: ROS Slave URI: [http://FM00351-u:40347/]
[rospy.impl.masterslave][INFO] 2022-02-14 15:38:31,995: _ready: http://FM00351-u:40347/
[xmlrpc][INFO] 2022-02-14 15:38:31,995: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-02-14 15:38:31,996: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2022-02-14 15:38:31,996: Registering publisher topic [/Robotiq2FGripperRobotOutput] type [robotiq_2f_gripper_control/Robotiq2FGripper_robot_output] with master
[rospy.init][INFO] 2022-02-14 15:38:32,095: registered with master
[rospy.rosout][INFO] 2022-02-14 15:38:32,096: initializing /rosout core topic
[rospy.rosout][INFO] 2022-02-14 15:38:32,098: connected to core topic /rosout
[rospy.simtime][INFO] 2022-02-14 15:38:32,100: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-02-14 15:38:32,108: topic[/Robotiq2FGripperRobotOutput] adding connection to [/robotiq2FGripper], count 0
[rospy.internal][INFO] 2022-02-14 15:38:32,388: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-02-14 15:39:46,419: topic[/Robotiq2FGripperRobotOutput] adding connection to [/rostopic_3258_1644853186185], count 1
[rospy.core][INFO] 2022-02-14 15:40:38,444: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-02-14 15:40:38,448: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-02-14 15:40:38,448: topic[/Robotiq2FGripperRobotOutput] removing connection to /robotiq2FGripper
[rospy.internal][INFO] 2022-02-14 15:40:38,449: topic[/Robotiq2FGripperRobotOutput] removing connection to /rostopic_3258_1644853186185
[rospy.impl.masterslave][INFO] 2022-02-14 15:40:38,449: signal-2
[rospy.core][INFO] 2022-02-14 15:40:41,626: signal_shutdown [atexit]
[rospy.client][INFO] 2022-02-23 10:46:29,793: init_node, name[/fm_gripper_action_server], pid[11386]
[xmlrpc][INFO] 2022-02-23 10:46:29,800: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-02-23 10:46:29,800: Started XML-RPC server [http://FM00351-u:38205/]
[rospy.init][INFO] 2022-02-23 10:46:29,800: ROS Slave URI: [http://FM00351-u:38205/]
[rospy.impl.masterslave][INFO] 2022-02-23 10:46:29,800: _ready: http://FM00351-u:38205/
[rospy.registration][INFO] 2022-02-23 10:46:29,801: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-02-23 10:46:29,801: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-02-23 10:46:29,901: registered with master
[rospy.rosout][INFO] 2022-02-23 10:46:29,901: initializing /rosout core topic
[rospy.rosout][INFO] 2022-02-23 10:46:29,906: connected to core topic /rosout
[rospy.simtime][INFO] 2022-02-23 10:46:29,907: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-02-23 10:46:30,121: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2022-02-23 11:02:31,566: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-02-23 11:02:31,572: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2022-02-23 11:02:31,572: signal-2
[rospy.core][INFO] 2022-02-23 11:02:32,188: signal_shutdown [atexit]
[rospy.client][INFO] 2022-02-23 11:02:34,071: init_node, name[/fm_gripper_action_server], pid[11796]
[xmlrpc][INFO] 2022-02-23 11:02:34,071: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-02-23 11:02:34,072: Started XML-RPC server [http://FM00351-u:38683/]
[rospy.init][INFO] 2022-02-23 11:02:34,072: ROS Slave URI: [http://FM00351-u:38683/]
[rospy.impl.masterslave][INFO] 2022-02-23 11:02:34,072: _ready: http://FM00351-u:38683/
[rospy.registration][INFO] 2022-02-23 11:02:34,073: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-02-23 11:02:34,073: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-02-23 11:02:34,173: registered with master
[rospy.rosout][INFO] 2022-02-23 11:02:34,173: initializing /rosout core topic
[rospy.rosout][INFO] 2022-02-23 11:02:34,177: connected to core topic /rosout
[rospy.simtime][INFO] 2022-02-23 11:02:34,179: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-02-23 11:02:34,404: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2022-02-23 11:03:44,480: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-02-23 11:03:44,485: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2022-02-23 11:03:44,485: signal-2
[rospy.core][INFO] 2022-02-23 11:03:44,603: signal_shutdown [atexit]
[rospy.client][INFO] 2022-02-23 11:09:49,111: init_node, name[/fm_gripper_action_server], pid[13825]
[xmlrpc][INFO] 2022-02-23 11:09:49,111: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-02-23 11:09:49,111: Started XML-RPC server [http://FM00351-u:42429/]
[rospy.init][INFO] 2022-02-23 11:09:49,112: ROS Slave URI: [http://FM00351-u:42429/]
[rospy.impl.masterslave][INFO] 2022-02-23 11:09:49,112: _ready: http://FM00351-u:42429/
[rospy.registration][INFO] 2022-02-23 11:09:49,113: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-02-23 11:09:49,113: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-02-23 11:09:49,212: registered with master
[rospy.rosout][INFO] 2022-02-23 11:09:49,213: initializing /rosout core topic
[rospy.registration][ERROR] 2022-02-23 11:09:49,214: [Errno 111] Connection refused
Unable to register with master node [http://localhost:11311]: master may not be running yet. Will keep trying.
[rospy.core][INFO] 2022-02-23 11:09:51,362: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2022-02-23 11:09:51,363: cannot unregister with master due to network issues
[rospy.impl.masterslave][INFO] 2022-02-23 11:09:51,364: signal-2
[rospy.core][INFO] 2022-02-23 11:09:56,464: signal_shutdown [signal-2]
[rospy.rosout][INFO] 2022-02-23 11:09:56,465: connected to core topic /rosout
[rospy.simtime][ERROR] 2022-02-23 11:09:56,465: Unable to initialize /clock: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/simtime.py", line 79, in init_simtime
    if not _is_use_simtime():
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/simtime.py", line 60, in _is_use_simtime
    code, msg, val = m.getParam(rospy.names.get_caller_id(), _USE_SIMTIME)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 670, in _ServerProxy__request
    self, methodname, params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 860, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 837, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rospy.core][INFO] 2022-02-23 11:09:56,466: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-09 08:51:44,203: init_node, name[/fm_gripper_action_server], pid[1113]
[xmlrpc][INFO] 2022-03-09 08:51:44,204: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 08:51:44,204: Started XML-RPC server [http://FM00351-u:35611/]
[rospy.init][INFO] 2022-03-09 08:51:44,204: ROS Slave URI: [http://FM00351-u:35611/]
[rospy.impl.masterslave][INFO] 2022-03-09 08:51:44,205: _ready: http://FM00351-u:35611/
[rospy.registration][INFO] 2022-03-09 08:51:44,205: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-09 08:51:44,205: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-09 08:51:44,305: registered with master
[rospy.rosout][INFO] 2022-03-09 08:51:44,306: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 08:51:44,310: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 08:51:44,312: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 08:51:44,537: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-09 08:52:28,367: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:45627/], count 0
[rospy.internal][INFO] 2022-03-09 08:52:28,369: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 08:52:28,369: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 08:52:28,370: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:45627/], count 0
[rospy.internal][INFO] 2022-03-09 08:52:28,371: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rosout][INFO] 2022-03-09 08:52:28,402: state: initializing
[rosout][INFO] 2022-03-09 08:52:28,403: controller is started now
[rospy.internal][INFO] 2022-03-09 08:52:28,447: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][INFO] 2022-03-09 09:01:45,075: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:33915/], count 0
[rosout][ERROR] 2022-03-09 09:01:58,236: Exception in your execute callback: name 'r' is not defined
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 38, in execute
    Robotiq2FGripperSlipController().controller()
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 798, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 771, in askForInput
    return input(strAskForCommand)
  File "<string>", line 1, in <module>
NameError: name 'r' is not defined

[rospy.internal][ERROR] 2022-03-09 09:01:58,267: Unable to initiate TCP/IP socket to FM00351-u:35069 (http://FM00351-u:45627/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-09 09:01:58,267: Unable to initiate TCP/IP socket to FM00351-u:35069 (http://FM00351-u:45627/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2022-03-09 09:01:58,404: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-09 09:01:58,406: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-09 09:01:58,532: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 09:01:58,583: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 09:01:58,584: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-09 09:01:59,276: Unknown error initiating TCP/IP socket to FM00351-u:35069 (http://FM00351-u:45627/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 09:01:59,277: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:45627/
[rospy.internal][WARNING] 2022-03-09 09:01:59,277: Unknown error initiating TCP/IP socket to FM00351-u:35069 (http://FM00351-u:45627/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 09:01:59,278: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:45627/
[rospy.internal][INFO] 2022-03-09 09:02:05,706: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:41509/], count 0
[rospy.internal][INFO] 2022-03-09 09:02:05,707: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:41509/], count 0
[rospy.internal][INFO] 2022-03-09 09:02:05,708: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 09:02:05,708: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 09:02:05,709: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rosout][INFO] 2022-03-09 09:02:05,725: state: initializing
[rosout][INFO] 2022-03-09 09:02:05,726: controller is started now
[rospy.core][INFO] 2022-03-09 09:15:50,933: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-09 09:15:50,938: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 09:15:50,938: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 09:15:50,938: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-09 09:15:50,938: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 09:15:50,938: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-09 09:15:50,938: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:41509/
[rospy.internal][WARNING] 2022-03-09 09:15:50,939: Unknown error initiating TCP/IP socket to FM00351-u:38515 (http://FM00351-u:41509/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
AttributeError: 'NoneType' object has no attribute 'buff_size'

[rospy.internal][INFO] 2022-03-09 09:15:50,939: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:41509/
[rospy.internal][INFO] 2022-03-09 09:15:50,939: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:33915/
[rospy.impl.masterslave][INFO] 2022-03-09 09:15:50,939: signal-2
[rosout][ERROR] 2022-03-09 09:15:52,023: Exception in your execute callback: 
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 38, in execute
    Robotiq2FGripperSlipController().controller()
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 798, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 771, in askForInput
    return input(strAskForCommand)
EOFError

[rospy.core][INFO] 2022-03-09 09:15:52,127: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-09 09:58:16,695: init_node, name[/fm_gripper_action_server], pid[3463]
[xmlrpc][INFO] 2022-03-09 09:58:16,695: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 09:58:16,695: Started XML-RPC server [http://FM00351-u:33087/]
[rospy.init][INFO] 2022-03-09 09:58:16,695: ROS Slave URI: [http://FM00351-u:33087/]
[rospy.impl.masterslave][INFO] 2022-03-09 09:58:16,696: _ready: http://FM00351-u:33087/
[rospy.registration][INFO] 2022-03-09 09:58:16,696: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-09 09:58:16,696: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-09 09:58:16,796: registered with master
[rospy.rosout][INFO] 2022-03-09 09:58:16,796: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 09:58:16,801: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 09:58:16,802: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 09:58:17,026: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-09 09:58:43,002: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 09:58:43,002: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 09:58:43,003: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 09:58:43,086: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35581/], count 0
[rospy.internal][INFO] 2022-03-09 09:58:43,087: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35581/], count 0
[rosout][INFO] 2022-03-09 09:58:43,111: state: initializing
[rosout][INFO] 2022-03-09 09:58:43,112: controller is started now
[rospy.internal][INFO] 2022-03-09 09:58:43,219: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.core][INFO] 2022-03-09 10:08:58,079: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-09 10:08:58,083: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:08:58,083: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:08:58,083: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-09 10:08:58,084: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:08:58,084: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-09 10:08:58,084: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35581/
[rospy.internal][INFO] 2022-03-09 10:08:58,084: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35581/
[rospy.impl.masterslave][INFO] 2022-03-09 10:08:58,084: signal-2
[rosout][ERROR] 2022-03-09 10:08:59,157: Exception in your execute callback: unexpected EOF while parsing (<string>, line 0)
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 38, in execute
    command = 'cal'
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 798, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 771, in askForInput
    return input(strAskForCommand)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

[rospy.core][INFO] 2022-03-09 10:08:59,260: signal_shutdown [signal-2]
[rospy.core][INFO] 2022-03-09 10:08:59,261: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-09 10:24:20,591: init_node, name[/fm_gripper_action_server], pid[5496]
[xmlrpc][INFO] 2022-03-09 10:24:20,591: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 10:24:20,591: Started XML-RPC server [http://FM00351-u:37517/]
[rospy.init][INFO] 2022-03-09 10:24:20,591: ROS Slave URI: [http://FM00351-u:37517/]
[rospy.impl.masterslave][INFO] 2022-03-09 10:24:20,591: _ready: http://FM00351-u:37517/
[rospy.registration][INFO] 2022-03-09 10:24:20,592: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-09 10:24:20,592: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-09 10:24:20,692: registered with master
[rospy.rosout][INFO] 2022-03-09 10:24:20,692: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 10:24:20,696: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 10:24:20,698: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 10:24:20,965: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-09 10:24:23,646: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:24:23,647: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:24:23,647: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:24:23,674: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:36411/], count 0
[rospy.internal][INFO] 2022-03-09 10:24:23,674: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:36411/], count 0
[rosout][INFO] 2022-03-09 10:24:23,710: state: initializing
[rosout][INFO] 2022-03-09 10:24:23,711: controller is started now
[rospy.internal][INFO] 2022-03-09 10:24:23,738: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:46323/], count 0
[rospy.internal][INFO] 2022-03-09 10:24:23,788: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.core][INFO] 2022-03-09 10:24:42,729: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-09 10:24:42,737: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:24:42,739: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:24:42,740: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-09 10:24:42,740: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:24:42,742: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-09 10:24:42,742: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:36411/
[rospy.internal][INFO] 2022-03-09 10:24:42,742: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:36411/
[rospy.internal][INFO] 2022-03-09 10:24:42,743: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:46323/
[rospy.impl.masterslave][INFO] 2022-03-09 10:24:42,744: signal-2
[rosout][INFO] 2022-03-09 10:24:42,745: state: inactive
[rospy.core][INFO] 2022-03-09 10:24:42,922: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-09 10:26:42,277: init_node, name[/fm_gripper_action_server], pid[5601]
[xmlrpc][INFO] 2022-03-09 10:26:42,277: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 10:26:42,277: Started XML-RPC server [http://FM00351-u:43543/]
[rospy.init][INFO] 2022-03-09 10:26:42,278: ROS Slave URI: [http://FM00351-u:43543/]
[rospy.impl.masterslave][INFO] 2022-03-09 10:26:42,278: _ready: http://FM00351-u:43543/
[rospy.registration][INFO] 2022-03-09 10:26:42,278: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-09 10:26:42,278: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-09 10:26:42,378: registered with master
[rospy.rosout][INFO] 2022-03-09 10:26:42,378: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 10:26:42,382: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 10:26:42,382: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 10:26:42,601: topic[/rosout] adding connection to [/rosout], count 0
[rospy.core][INFO] 2022-03-09 10:27:02,125: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-09 10:27:02,128: topic[/rosout] removing connection to /rosout
[rospy.impl.masterslave][INFO] 2022-03-09 10:27:02,128: signal-2
[rospy.core][INFO] 2022-03-09 10:27:02,292: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-09 10:27:10,725: init_node, name[/fm_gripper_action_server], pid[5708]
[xmlrpc][INFO] 2022-03-09 10:27:10,725: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 10:27:10,725: Started XML-RPC server [http://FM00351-u:32949/]
[rospy.init][INFO] 2022-03-09 10:27:10,725: ROS Slave URI: [http://FM00351-u:32949/]
[rospy.impl.masterslave][INFO] 2022-03-09 10:27:10,725: _ready: http://FM00351-u:32949/
[rospy.registration][INFO] 2022-03-09 10:27:10,726: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-09 10:27:10,726: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-09 10:27:10,826: registered with master
[rospy.rosout][INFO] 2022-03-09 10:27:10,826: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 10:27:10,828: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 10:27:10,828: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 10:27:10,950: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-09 10:28:09,303: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:28:09,304: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:28:09,304: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:28:09,367: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:33517/], count 0
[rospy.internal][INFO] 2022-03-09 10:28:09,367: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:33517/], count 0
[rosout][INFO] 2022-03-09 10:28:09,399: state: initializing
[rosout][INFO] 2022-03-09 10:28:09,401: controller is started now
[rospy.internal][INFO] 2022-03-09 10:28:09,433: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:46323/], count 0
[rospy.internal][INFO] 2022-03-09 10:28:09,498: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][WARNING] 2022-03-09 10:28:10,285: Unknown error initiating TCP/IP socket to FM00351-u:36233 (http://FM00351-u:33517/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:28:10,287: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:33517/
[rospy.internal][WARNING] 2022-03-09 10:28:10,287: Unknown error initiating TCP/IP socket to FM00351-u:36233 (http://FM00351-u:33517/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-09 10:28:10,298: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:33517/
[rospy.internal][INFO] 2022-03-09 10:28:10,434: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:28:10,434: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:28:10,434: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:28:34,046: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:28:34,061: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:28:34,063: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35917/], count 0
[rospy.internal][INFO] 2022-03-09 10:28:34,066: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35917/], count 0
[rospy.internal][INFO] 2022-03-09 10:28:34,071: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][ERROR] 2022-03-09 10:28:34,815: Unable to initiate TCP/IP socket to FM00351-u:46811 (http://FM00351-u:35917/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2022-03-09 10:28:34,816: Unknown error initiating TCP/IP socket to FM00351-u:46811 (http://FM00351-u:35917/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:28:34,823: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35917/
[rosout][WARNING] 2022-03-09 10:28:34,970: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-09 10:28:35,024: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-09 10:28:35,052: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:28:35,086: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:28:35,086: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-09 10:28:35,833: Unknown error initiating TCP/IP socket to FM00351-u:46811 (http://FM00351-u:35917/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:28:35,836: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35917/
[rospy.core][INFO] 2022-03-09 10:29:05,676: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-09 10:29:05,716: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-09 10:29:05,717: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-09 10:29:05,718: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:46323/
[rospy.impl.masterslave][INFO] 2022-03-09 10:29:05,727: signal-2
[rosout][INFO] 2022-03-09 10:29:05,728: state: inactive
[rospy.core][INFO] 2022-03-09 10:29:05,859: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-09 10:29:08,400: init_node, name[/fm_gripper_action_server], pid[6394]
[xmlrpc][INFO] 2022-03-09 10:29:08,400: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 10:29:08,401: Started XML-RPC server [http://FM00351-u:44931/]
[rospy.init][INFO] 2022-03-09 10:29:08,401: ROS Slave URI: [http://FM00351-u:44931/]
[rospy.impl.masterslave][INFO] 2022-03-09 10:29:08,401: _ready: http://FM00351-u:44931/
[rospy.registration][INFO] 2022-03-09 10:29:08,402: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-09 10:29:08,402: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-09 10:29:08,501: registered with master
[rospy.rosout][INFO] 2022-03-09 10:29:08,502: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 10:29:08,504: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 10:29:08,504: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 10:29:08,733: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-09 10:29:12,319: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:12,319: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:12,319: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:12,384: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35795/], count 0
[rospy.internal][INFO] 2022-03-09 10:29:12,384: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35795/], count 0
[rosout][INFO] 2022-03-09 10:29:12,414: state: initializing
[rosout][INFO] 2022-03-09 10:29:12,416: controller is started now
[rospy.internal][INFO] 2022-03-09 10:29:12,448: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:46323/], count 0
[rospy.internal][INFO] 2022-03-09 10:29:12,456: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][ERROR] 2022-03-09 10:29:12,799: Unable to initiate TCP/IP socket to FM00351-u:46721 (http://FM00351-u:35795/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-09 10:29:12,800: Unable to initiate TCP/IP socket to FM00351-u:46721 (http://FM00351-u:35795/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-03-09 10:29:12,948: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:29:12,948: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:29:12,948: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-09 10:29:13,804: Unknown error initiating TCP/IP socket to FM00351-u:46721 (http://FM00351-u:35795/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:29:13,805: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35795/
[rospy.internal][WARNING] 2022-03-09 10:29:13,805: Unknown error initiating TCP/IP socket to FM00351-u:46721 (http://FM00351-u:35795/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:29:13,810: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35795/
[rospy.internal][INFO] 2022-03-09 10:29:24,808: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:24,812: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:24,818: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:24,849: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:36283/], count 0
[rospy.internal][INFO] 2022-03-09 10:29:24,852: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:36283/], count 0
[rospy.internal][ERROR] 2022-03-09 10:29:25,516: Unable to initiate TCP/IP socket to FM00351-u:35807 (http://FM00351-u:36283/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2022-03-09 10:29:25,519: Unknown error initiating TCP/IP socket to FM00351-u:35807 (http://FM00351-u:36283/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 561, in connect
    self.write_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 642, in write_header
    self.stat_bytes += write_ros_handshake_header(sock, protocol.get_header_fields())
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 417, in write_ros_handshake_header
    sock.sendall(s)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-03-09 10:29:25,521: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:36283/
[rosout][WARNING] 2022-03-09 10:29:25,645: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-09 10:29:25,657: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rosout][WARNING] 2022-03-09 10:29:25,665: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-09 10:29:25,683: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-09 10:29:25,714: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:29:25,859: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:29:25,862: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-09 10:29:26,529: Unknown error initiating TCP/IP socket to FM00351-u:35807 (http://FM00351-u:36283/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:29:26,536: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:36283/
[rospy.core][INFO] 2022-03-09 10:29:47,766: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-09 10:29:47,781: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-09 10:29:47,781: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-09 10:29:47,783: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:46323/
[rospy.impl.masterslave][INFO] 2022-03-09 10:29:47,785: signal-2
[rosout][INFO] 2022-03-09 10:29:47,789: state: inactive
[rospy.core][INFO] 2022-03-09 10:29:48,412: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-09 10:29:52,180: init_node, name[/fm_gripper_action_server], pid[6580]
[xmlrpc][INFO] 2022-03-09 10:29:52,181: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-09 10:29:52,181: Started XML-RPC server [http://FM00351-u:32805/]
[rospy.init][INFO] 2022-03-09 10:29:52,181: ROS Slave URI: [http://FM00351-u:32805/]
[rospy.impl.masterslave][INFO] 2022-03-09 10:29:52,181: _ready: http://FM00351-u:32805/
[xmlrpc][INFO] 2022-03-09 10:29:52,182: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-03-09 10:29:52,182: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-03-09 10:29:52,282: registered with master
[rospy.rosout][INFO] 2022-03-09 10:29:52,282: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-09 10:29:52,284: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-09 10:29:52,285: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-09 10:29:52,520: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-09 10:29:56,344: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:56,344: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:56,344: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:29:56,363: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:40537/], count 0
[rospy.internal][INFO] 2022-03-09 10:29:56,364: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:40537/], count 0
[rosout][INFO] 2022-03-09 10:29:56,394: state: initializing
[rosout][INFO] 2022-03-09 10:29:56,396: controller is started now
[rospy.internal][INFO] 2022-03-09 10:29:56,429: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:46323/], count 0
[rospy.internal][INFO] 2022-03-09 10:29:56,454: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rosout][WARNING] 2022-03-09 10:29:56,787: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-09 10:29:56,789: Unable to initiate TCP/IP socket to FM00351-u:38561 (http://FM00351-u:40537/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-09 10:29:56,789: Unable to initiate TCP/IP socket to FM00351-u:38561 (http://FM00351-u:40537/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-09 10:29:56,789: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-09 10:29:56,929: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:29:56,929: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:29:56,929: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-09 10:29:57,796: Unknown error initiating TCP/IP socket to FM00351-u:38561 (http://FM00351-u:40537/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-03-09 10:29:57,797: Unknown error initiating TCP/IP socket to FM00351-u:38561 (http://FM00351-u:40537/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:29:57,797: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:40537/
[rospy.internal][INFO] 2022-03-09 10:29:57,798: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:40537/
[rospy.internal][INFO] 2022-03-09 10:30:00,556: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:30:00,560: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:30:00,567: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:30:00,577: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:46577/], count 0
[rospy.internal][INFO] 2022-03-09 10:30:00,584: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:46577/], count 0
[rospy.internal][ERROR] 2022-03-09 10:30:01,205: Unable to initiate TCP/IP socket to FM00351-u:36477 (http://FM00351-u:46577/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][WARNING] 2022-03-09 10:30:01,206: Unknown error initiating TCP/IP socket to FM00351-u:36477 (http://FM00351-u:46577/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-09 10:30:01,219: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:46577/
[rosout][WARNING] 2022-03-09 10:30:01,339: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-09 10:30:01,342: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-09 10:30:01,495: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:30:01,584: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:30:01,588: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-09 10:30:02,216: Unknown error initiating TCP/IP socket to FM00351-u:36477 (http://FM00351-u:46577/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:30:02,217: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:46577/
[rospy.internal][INFO] 2022-03-09 10:30:07,266: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:30:07,274: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:30:07,290: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-09 10:30:07,321: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:44945/], count 0
[rospy.internal][INFO] 2022-03-09 10:30:07,328: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:44945/], count 0
[rospy.internal][WARNING] 2022-03-09 10:30:07,973: Unknown error initiating TCP/IP socket to FM00351-u:41445 (http://FM00351-u:44945/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-03-09 10:30:07,976: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:44945/
[rospy.internal][ERROR] 2022-03-09 10:30:07,976: Unable to initiate TCP/IP socket to FM00351-u:41445 (http://FM00351-u:44945/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-03-09 10:30:08,294: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:30:08,335: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-09 10:30:08,336: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-09 10:30:08,996: Unknown error initiating TCP/IP socket to FM00351-u:41445 (http://FM00351-u:44945/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 10:30:09,000: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:44945/
[rospy.internal][INFO] 2022-03-09 15:08:18,030: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][WARNING] 2022-03-09 15:09:44,343: Unknown error initiating TCP/IP socket to FM00351-u:36389 (http://FM00351-u:46323/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-09 15:09:44,446: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:46323/
[rospy.internal][INFO] 2022-03-09 15:11:20,126: topic[/rosout] removing connection to /rosout
[rospy.client][INFO] 2022-03-10 09:55:30,486: init_node, name[/fm_gripper_action_server], pid[991]
[xmlrpc][INFO] 2022-03-10 09:55:30,487: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-10 09:55:30,487: Started XML-RPC server [http://FM00351-u:43977/]
[rospy.init][INFO] 2022-03-10 09:55:30,488: ROS Slave URI: [http://FM00351-u:43977/]
[rospy.impl.masterslave][INFO] 2022-03-10 09:55:30,488: _ready: http://FM00351-u:43977/
[rospy.registration][INFO] 2022-03-10 09:55:30,489: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-10 09:55:30,489: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-10 09:55:30,588: registered with master
[rospy.rosout][INFO] 2022-03-10 09:55:30,589: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-10 09:55:30,593: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-10 09:55:30,594: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-10 09:55:30,863: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,037: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:42849/], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,037: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:42849/], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,064: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,065: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,065: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rosout][INFO] 2022-03-10 09:55:56,071: state: initializing
[rosout][INFO] 2022-03-10 09:55:56,072: controller is started now
[rospy.internal][INFO] 2022-03-10 09:55:56,103: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:44707/], count 0
[rospy.internal][INFO] 2022-03-10 09:55:56,132: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][WARNING] 2022-03-10 09:57:17,190: Unknown error initiating TCP/IP socket to FM00351-u:39451 (http://FM00351-u:42849/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:57:17,206: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:42849/
[rospy.internal][WARNING] 2022-03-10 09:57:17,209: Unknown error initiating TCP/IP socket to FM00351-u:39451 (http://FM00351-u:42849/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:57:17,223: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:17,225: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:42849/
[rospy.internal][INFO] 2022-03-10 09:57:17,226: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:17,227: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:19,715: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,772: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,788: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,792: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35639/], count 0
[rospy.internal][INFO] 2022-03-10 09:57:19,816: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35639/], count 0
[rospy.internal][WARNING] 2022-03-10 09:57:20,106: Unknown error initiating TCP/IP socket to FM00351-u:35931 (http://FM00351-u:35639/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-03-10 09:57:20,112: Unknown error initiating TCP/IP socket to FM00351-u:35931 (http://FM00351-u:35639/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:57:20,120: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35639/
[rospy.internal][INFO] 2022-03-10 09:57:20,144: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35639/
[rospy.internal][INFO] 2022-03-10 09:57:20,290: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:20,293: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:20,294: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.core][INFO] 2022-03-10 09:57:24,230: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-10 09:57:24,277: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-10 09:57:24,278: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-10 09:57:24,279: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:44707/
[rospy.impl.masterslave][INFO] 2022-03-10 09:57:24,280: signal-2
[rosout][INFO] 2022-03-10 09:57:24,282: state: inactive
[rospy.core][INFO] 2022-03-10 09:57:24,416: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-10 09:57:26,802: init_node, name[/fm_gripper_action_server], pid[1577]
[xmlrpc][INFO] 2022-03-10 09:57:26,802: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-10 09:57:26,802: Started XML-RPC server [http://FM00351-u:42897/]
[rospy.init][INFO] 2022-03-10 09:57:26,803: ROS Slave URI: [http://FM00351-u:42897/]
[rospy.impl.masterslave][INFO] 2022-03-10 09:57:26,803: _ready: http://FM00351-u:42897/
[rospy.registration][INFO] 2022-03-10 09:57:26,804: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-10 09:57:26,804: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-10 09:57:26,903: registered with master
[rospy.rosout][INFO] 2022-03-10 09:57:26,903: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-10 09:57:26,906: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-10 09:57:26,906: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-10 09:57:27,133: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,637: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,638: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,638: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,686: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:34975/], count 0
[rospy.internal][INFO] 2022-03-10 09:57:31,687: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:34975/], count 0
[rospy.internal][ERROR] 2022-03-10 09:57:31,722: Unable to initiate TCP/IP socket to FM00351-u:37949 (http://FM00351-u:34975/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-10 09:57:31,722: Unable to initiate TCP/IP socket to FM00351-u:37949 (http://FM00351-u:34975/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rosout][WARNING] 2022-03-10 09:57:31,721: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-10 09:57:31,723: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][INFO] 2022-03-10 09:57:32,115: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:32,186: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:57:32,186: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-10 09:57:32,723: Unknown error initiating TCP/IP socket to FM00351-u:37949 (http://FM00351-u:34975/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:57:32,723: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:34975/
[rospy.internal][WARNING] 2022-03-10 09:57:32,723: Unknown error initiating TCP/IP socket to FM00351-u:37949 (http://FM00351-u:34975/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:57:32,724: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:34975/
[rospy.internal][INFO] 2022-03-10 09:58:09,434: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,434: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,435: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,470: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:35949/], count 0
[rospy.internal][INFO] 2022-03-10 09:58:09,472: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:35949/], count 0
[rosout][INFO] 2022-03-10 09:58:09,488: state: initializing
[rosout][INFO] 2022-03-10 09:58:09,490: controller is started now
[rospy.internal][INFO] 2022-03-10 09:58:09,519: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][ERROR] 2022-03-10 09:58:09,544: Unable to initiate TCP/IP socket to FM00351-u:45051 (http://FM00351-u:35949/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-10 09:58:09,545: Unable to initiate TCP/IP socket to FM00351-u:45051 (http://FM00351-u:35949/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-03-10 09:58:09,915: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:58:09,970: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 09:58:09,971: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-10 09:58:10,546: Unknown error initiating TCP/IP socket to FM00351-u:45051 (http://FM00351-u:35949/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:58:10,546: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:35949/
[rospy.internal][WARNING] 2022-03-10 09:58:10,546: Unknown error initiating TCP/IP socket to FM00351-u:45051 (http://FM00351-u:35949/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 09:58:10,547: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:35949/
[rospy.internal][INFO] 2022-03-10 09:58:14,790: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:44707/], count 0
[rospy.core][INFO] 2022-03-10 09:58:30,989: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-10 09:58:30,993: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-10 09:58:30,993: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-10 09:58:30,994: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:44707/
[rospy.impl.masterslave][INFO] 2022-03-10 09:58:30,994: signal-2
[rosout][ERROR] 2022-03-10 09:58:32,536: Exception in your execute callback: unexpected EOF while parsing (<string>, line 0)
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 54, in execute
    Robotiq2FGripperSlipController().controller()
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 798, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 771, in askForInput
    return input(strAskForCommand)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

[rospy.core][INFO] 2022-03-10 09:58:32,638: signal_shutdown [signal-2]
[rospy.core][INFO] 2022-03-10 09:58:32,639: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-10 10:07:28,324: init_node, name[/fm_gripper_action_server], pid[1746]
[xmlrpc][INFO] 2022-03-10 10:07:28,325: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-10 10:07:28,325: Started XML-RPC server [http://FM00351-u:38627/]
[rospy.init][INFO] 2022-03-10 10:07:28,325: ROS Slave URI: [http://FM00351-u:38627/]
[rospy.impl.masterslave][INFO] 2022-03-10 10:07:28,325: _ready: http://FM00351-u:38627/
[xmlrpc][INFO] 2022-03-10 10:07:28,326: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-03-10 10:07:28,327: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-03-10 10:07:28,426: registered with master
[rospy.rosout][INFO] 2022-03-10 10:07:28,427: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-10 10:07:28,431: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-10 10:07:28,432: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-10 10:07:28,645: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-10 10:07:39,896: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:07:39,897: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:07:39,897: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:07:39,983: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:41089/], count 0
[rospy.internal][INFO] 2022-03-10 10:07:39,984: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:41089/], count 0
[rosout][INFO] 2022-03-10 10:07:39,998: state: initializing
[rosout][INFO] 2022-03-10 10:07:40,000: controller is started now
[rospy.internal][INFO] 2022-03-10 10:07:40,067: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][ERROR] 2022-03-10 10:07:40,965: Unable to initiate TCP/IP socket to FM00351-u:46527 (http://FM00351-u:41089/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-10 10:07:40,966: Unable to initiate TCP/IP socket to FM00351-u:46527 (http://FM00351-u:41089/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-03-10 10:07:40,983: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:07:40,984: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:07:40,984: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rosout][WARNING] 2022-03-10 10:07:41,172: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][ERROR] 2022-03-10 10:07:41,175: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2022-03-10 10:07:41,968: Unknown error initiating TCP/IP socket to FM00351-u:46527 (http://FM00351-u:41089/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-03-10 10:07:41,969: Unknown error initiating TCP/IP socket to FM00351-u:46527 (http://FM00351-u:41089/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 10:07:41,969: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:41089/
[rospy.internal][INFO] 2022-03-10 10:07:41,969: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:41089/
[rosout][ERROR] 2022-03-10 10:08:14,485: Exception in your execute callback: name 'r' is not defined
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 54, in execute
    Robotiq2FGripperSlipController().controller()
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 798, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 771, in askForInput
    return input(strAskForCommand)
  File "<string>", line 1, in <module>
NameError: name 'r' is not defined

[rospy.core][INFO] 2022-03-10 10:08:20,110: signal_shutdown [signal-2]
[rospy.internal][INFO] 2022-03-10 10:08:20,115: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2022-03-10 10:08:20,116: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.impl.masterslave][INFO] 2022-03-10 10:08:20,116: signal-2
[rospy.core][INFO] 2022-03-10 10:08:20,240: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-10 10:08:23,379: init_node, name[/fm_gripper_action_server], pid[1835]
[xmlrpc][INFO] 2022-03-10 10:08:23,380: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-10 10:08:23,381: Started XML-RPC server [http://FM00351-u:43629/]
[rospy.init][INFO] 2022-03-10 10:08:23,381: ROS Slave URI: [http://FM00351-u:43629/]
[rospy.impl.masterslave][INFO] 2022-03-10 10:08:23,381: _ready: http://FM00351-u:43629/
[xmlrpc][INFO] 2022-03-10 10:08:23,382: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2022-03-10 10:08:23,382: Registering with master node http://localhost:11311
[rospy.init][INFO] 2022-03-10 10:08:23,482: registered with master
[rospy.rosout][INFO] 2022-03-10 10:08:23,482: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-10 10:08:23,486: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-10 10:08:23,488: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-10 10:08:23,718: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-10 10:08:27,339: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:08:27,340: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:08:27,340: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:08:27,419: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:33879/], count 0
[rospy.internal][INFO] 2022-03-10 10:08:27,419: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:33879/], count 0
[rosout][INFO] 2022-03-10 10:08:27,434: state: initializing
[rosout][INFO] 2022-03-10 10:08:27,436: controller is started now
[rospy.internal][INFO] 2022-03-10 10:08:27,479: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][ERROR] 2022-03-10 10:08:28,750: Unable to initiate TCP/IP socket to FM00351-u:46847 (http://FM00351-u:33879/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-10 10:08:28,752: Unable to initiate TCP/IP socket to FM00351-u:46847 (http://FM00351-u:33879/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-03-10 10:08:28,918: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:08:28,919: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rosout][WARNING] 2022-03-10 10:08:28,916: Inbound TCP/IP connection failed: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.
[rospy.internal][INFO] 2022-03-10 10:08:28,920: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][ERROR] 2022-03-10 10:08:28,920: Inbound TCP/IP connection failed:
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 325, in _tcp_server_callback
    header = read_ros_handshake_header(sock, StringIO(), buff_size)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 359, in read_ros_handshake_header
    raise ROSHandshakeException("connection from sender terminated before handshake header received. %s bytes were received. Please check sender for additional details."%b.tell())
ROSHandshakeException: connection from sender terminated before handshake header received. 0 bytes were received. Please check sender for additional details.

[rospy.internal][WARNING] 2022-03-10 10:08:29,754: Unknown error initiating TCP/IP socket to FM00351-u:46847 (http://FM00351-u:33879/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-03-10 10:08:29,754: Unknown error initiating TCP/IP socket to FM00351-u:46847 (http://FM00351-u:33879/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 10:08:29,754: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:33879/
[rospy.internal][INFO] 2022-03-10 10:08:29,755: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:33879/
[rospy.internal][INFO] 2022-03-10 10:08:30,738: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:44707/], count 0
[rospy.internal][WARNING] 2022-03-10 10:10:24,834: Unknown error initiating TCP/IP socket to FM00351-u:36811 (http://FM00351-u:44707/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2022-03-10 10:10:24,835: topic[/Robotiq2FGripperRobotInput] removing connection to http://FM00351-u:44707/
[rospy.internal][INFO] 2022-03-10 10:10:25,331: topic[/Robotiq2FGripperRobotOutput] removing connection to /Robotiq2FGripperRtuNode
[rospy.internal][INFO] 2022-03-10 10:10:25,832: topic[/rosout] removing connection to /rosout
[rospy.core][INFO] 2022-03-10 10:10:29,540: signal_shutdown [signal-2]
[rospy.registration][WARNING] 2022-03-10 10:10:29,541: cannot unregister with master due to network issues
[rospy.impl.masterslave][INFO] 2022-03-10 10:10:29,541: signal-2
[rospy.rosout][ERROR] 2022-03-10 10:10:31,007: Unable to report rosout: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/rosout.py", line 91, in _rosout
    disable_topics_ = rospy.get_param_cached("/rosout_disable_topics_generation", False)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/client.py", line 490, in get_param_cached
    return _param_server.get_param_cached(param_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/msproxy.py", line 168, in get_param_cached
    code, msg, value = self.target.subscribeParam(rospy.names.get_caller_id(), rospy.core.get_node_uri(), resolved_key)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
    return self.__send(self.__name, args)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/core.py", line 670, in _ServerProxy__request
    self, methodname, params)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
    self.send_content(h, request_body)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
    connection.endheaders(request_body)
  File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
    self.send(msg)
  File "/usr/lib/python2.7/httplib.py", line 860, in send
    self.connect()
  File "/usr/lib/python2.7/httplib.py", line 837, in connect
    self.timeout, self.source_address)
  File "/usr/lib/python2.7/socket.py", line 575, in create_connection
    raise err
error: [Errno 111] Connection refused

[rosout][ERROR] 2022-03-10 10:10:30,991: Exception in your execute callback: unexpected EOF while parsing (<string>, line 0)
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 54, in execute
    Robotiq2FGripperSlipController().controller()
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 798, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 771, in askForInput
    return input(strAskForCommand)
  File "<string>", line 0
    
    ^
SyntaxError: unexpected EOF while parsing

[rospy.core][INFO] 2022-03-10 10:10:31,108: signal_shutdown [signal-2]
[rospy.core][INFO] 2022-03-10 10:10:31,109: signal_shutdown [atexit]
[rospy.client][INFO] 2022-03-10 10:11:08,378: init_node, name[/fm_gripper_action_server], pid[1985]
[xmlrpc][INFO] 2022-03-10 10:11:08,378: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2022-03-10 10:11:08,379: Started XML-RPC server [http://FM00351-u:43419/]
[rospy.init][INFO] 2022-03-10 10:11:08,379: ROS Slave URI: [http://FM00351-u:43419/]
[rospy.impl.masterslave][INFO] 2022-03-10 10:11:08,379: _ready: http://FM00351-u:43419/
[rospy.registration][INFO] 2022-03-10 10:11:08,381: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2022-03-10 10:11:08,381: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2022-03-10 10:11:08,479: registered with master
[rospy.rosout][INFO] 2022-03-10 10:11:08,480: initializing /rosout core topic
[rospy.rosout][INFO] 2022-03-10 10:11:08,483: connected to core topic /rosout
[rospy.simtime][INFO] 2022-03-10 10:11:08,484: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2022-03-10 10:11:08,719: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2022-03-10 10:11:23,168: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:11:23,169: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:11:23,169: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:11:23,270: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:33605/], count 0
[rospy.internal][INFO] 2022-03-10 10:11:23,270: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:33605/], count 0
[rospy.internal][ERROR] 2022-03-10 10:11:23,499: Unable to initiate TCP/IP socket to FM00351-u:45059 (http://FM00351-u:33605/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-10 10:11:23,500: Unable to initiate TCP/IP socket to FM00351-u:45059 (http://FM00351-u:33605/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-03-10 10:11:23,769: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:11:23,769: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:11:23,769: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-10 10:11:24,501: Unknown error initiating TCP/IP socket to FM00351-u:45059 (http://FM00351-u:33605/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][WARNING] 2022-03-10 10:11:24,501: Unknown error initiating TCP/IP socket to FM00351-u:45059 (http://FM00351-u:33605/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 10:11:24,502: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:33605/
[rospy.internal][INFO] 2022-03-10 10:11:24,502: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:33605/
[rospy.internal][INFO] 2022-03-10 10:11:28,374: topic[/gripper_action_server/feedback] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:11:28,376: topic[/gripper_action_server/result] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:11:28,376: topic[/gripper_action_server/status] adding connection to [/gripper_action_client], count 0
[rospy.internal][INFO] 2022-03-10 10:11:28,489: topic[/gripper_action_server/goal] adding connection to [http://FM00351-u:36865/], count 0
[rospy.internal][INFO] 2022-03-10 10:11:28,489: topic[/gripper_action_server/cancel] adding connection to [http://FM00351-u:36865/], count 0
[rosout][INFO] 2022-03-10 10:11:28,527: state: initializing
[rosout][INFO] 2022-03-10 10:11:28,529: controller is started now
[rospy.internal][INFO] 2022-03-10 10:11:28,599: topic[/Robotiq2FGripperRobotOutput] adding connection to [/Robotiq2FGripperRtuNode], count 0
[rospy.internal][ERROR] 2022-03-10 10:11:40,475: Unable to initiate TCP/IP socket to FM00351-u:36335 (http://FM00351-u:36865/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][ERROR] 2022-03-10 10:11:40,475: Unable to initiate TCP/IP socket to FM00351-u:36335 (http://FM00351-u:36865/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 600, in _validate_header
    raise TransportInitError("remote error reported: %s"%header['error'])
TransportInitError: remote error reported: node shutting down

[rospy.internal][INFO] 2022-03-10 10:11:40,495: topic[/gripper_action_server/feedback] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:11:40,495: topic[/gripper_action_server/status] removing connection to /gripper_action_client
[rospy.internal][INFO] 2022-03-10 10:11:40,496: topic[/gripper_action_server/result] removing connection to /gripper_action_client
[rospy.internal][WARNING] 2022-03-10 10:11:41,476: Unknown error initiating TCP/IP socket to FM00351-u:36335 (http://FM00351-u:36865/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 10:11:41,477: topic[/gripper_action_server/goal] removing connection to http://FM00351-u:36865/
[rospy.internal][WARNING] 2022-03-10 10:11:41,477: Unknown error initiating TCP/IP socket to FM00351-u:36335 (http://FM00351-u:36865/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 560, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2022-03-10 10:11:41,477: topic[/gripper_action_server/cancel] removing connection to http://FM00351-u:36865/
[rospy.internal][INFO] 2022-03-10 10:12:21,566: topic[/Robotiq2FGripperRobotOutput] adding connection to [/rostopic_2252_1646907141358], count 1
[rospy.internal][INFO] 2022-03-10 10:12:30,026: topic[/Robotiq2FGripperRobotInput] adding connection to [http://FM00351-u:34165/], count 0
[rosout][ERROR] 2022-03-10 10:13:31,417: Exception in your execute callback: name 'r' is not defined
Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/actionlib/simple_action_server.py", line 289, in executeLoop
    self.execute_callback(goal)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/gripper_action_server.py", line 54, in execute
    Robotiq2FGripperSlipController().controller()
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 798, in controller
    inputs = self.askForInput(self.command)
  File "/home/ros/catkin_ws/src/fm_gripper_module/src/Robotiq2FGripperSlipController.py", line 771, in askForInput
    return input(strAskForCommand)
  File "<string>", line 1, in <module>
NameError: name 'r' is not defined

